spring.application.name=payments-service
server.port=8083

aws.region=${AWS_REGION:us-east-1}
aws.dynamodb.payments-table=${DYNAMODB_PAYMENTS_TABLE:payments}
aws.dynamodb.auto-create-table=${DYNAMODB_AUTO_CREATE_TABLE:true}
aws.dynamodb.endpoint=${DYNAMODB_ENDPOINT:}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
