spring.application.name=submissions-service
server.port=8082

aws.region=${AWS_REGION:us-east-1}
aws.dynamodb.submissions-table=${DYNAMODB_SUBMISSIONS_TABLE:submissions}
aws.dynamodb.auto-create-table=${DYNAMODB_AUTO_CREATE_TABLE:true}
aws.dynamodb.endpoint=${DYNAMODB_ENDPOINT:}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
