spring.application.name=api-gateway
server.port=8080
server.forward-headers-strategy=framework

security.jwt.secret=${SECURITY_JWT_SECRET:change-this-to-a-long-random-256-bit-secret-key}

services.submissions.url=${SERVICES_SUBMISSIONS_URL:http://localhost:8082}
services.payments.url=${SERVICES_PAYMENTS_URL:http://localhost:8083}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

api.base-url=${API_BASE_URL:http://localhost:8080}

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,metrics,env,beans,mappings
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessState.enabled=true
management.health.readinessState.enabled=true

logging.level.com.microservice.gateway=DEBUG
